print(5+2)
print(5-2)
print(5*2)
print(5 % 2)
print(5/2)
print(5**2)
print(5//2)

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("Sumanth"))
print(type("Talluri"))
print(type("India"))
